#include "defs/OpenhipifyDefs.h"

const std::string sOpenHipifyGenerated =
    "///////////////// Generated by Openhipify /////////////////\n";

const std::string sOpenHipifyGeneratedEnd =
    "///////////////////////////////////////////////////////////\n\n";

const std::string sOpenHipify = "[OpenHipify] ";
const std::string sErr = "error: ";
const std::string sWarn = "warning: ";
